os:
  - linux
#  - osx
  - windows
language: node_js
node_js:
  - "0.12.15"
  - "4.1.2"
  - "4.4.7"
script:
  - npm build
before_script:
  - npm install -g npm
  - npm install -g webpack
  - npm install
