os:
  - linux
#  - osx
  - windows
language: node_js
node_js:
  - "0.12"
  - "4.2.3"
script:
  - npm test
before_script:
  - npm install -g npm
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install
  - bower install
