os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
script:
  - npm test
before_script:
  - npm install -g npm
  - npm install -g grunt-cli
  - npm install
  - bower install
